modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="Jaron Cabral"
description='''
Earth becomes a rogue planet. The sun recedes, the world freezes, and survival shifts underground.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="frozendawn.mixins.json"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="optional"
    reason="Adds in-game guide book with rendered recipes"
    versionRange="[1.21.1-90,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="toughasnails"
    type="optional"
    reason="Integrates apocalypse temperature with TaN's body temperature system"
    versionRange="[10.0.0,)"
    ordering="AFTER"
    side="BOTH"
